// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

// Hard‑coded to Visionforge‑org project.
// Get these from Supabase Dashboard → Project Settings → API.
const SUPABASE_URL = "https://cchmnskagdcixrafeyfh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "YOUR_PUBLIC_ANON_KEY_HERE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
